apiVersion: v2
appVersion: develop-c082b60
dependencies:
- condition: ingress-nginx.enabled
  name: ingress-nginx
  repository: https://kubernetes.github.io/ingress-nginx
  version: 4.2.5
- condition: mongodb.enabled
  name: mongodb
  repository: https://charts.bitnami.com/bitnami/mongodb
  version: 13.1.5
- condition: redis.enabled
  name: redis
  repository: https://charts.bitnami.com/bitnami/redis
  version: 17.1.7
- condition: sheba.enabled
  name: sheba
  repository: ""
- condition: demo.enabled
  name: demo
  repository: ""
description: A helm chart for True Medical Report
name: truemedicalreport
type: application
version: 1.0.0
