global:
  debug: false
  baseDir: /path/to/chart/dir/..
  expose:
    host: true-medical-report
    class: nginx
    tls:
      enabled: false
      secretName: tls-tmr-ingress
  helpers:
    busybox:
      image: busybox
dal:
  port: 80
  replicas: 1
  ingress:
    annotations: {}
  repository:
    image: guydo/tmr-dal
    tag: latest
  volumeMappings:
    - relativePath: src/dal/tmr
      containerPath: /opt/dal/tmr
    - relativePath: src/common/tmr_common
      containerPath: /opt/common/tmr_common
backend:
  port: 80
  replicas: 1
  ingress:
    annotations: {}
  repository:
    image: guydo/tmr-backend
    tag: latest
  volumeMappings:
    - relativePath: src/dev/config
      containerPath: /opt/config
    - relativePath: src/backend/tmr
      containerPath: /opt/backend/tmr
    - relativePath: src/common/tmr_common
      containerPath: /opt/common/tmr_common
frontend:
  port: 3000
  replicas: 1
  ingress:
    annotations: {}
  repository:
    image: guydo/tmr-frontend
    tag: latest
  volumeMappings:
    - relativePath: src/frontend/tmr/src
      containerPath: /opt/frontend/tmr/src
    - relativePath: src/frontend/tmr/public
      containerPath: /opt/frontend/tmr/public
digest:
  type: sheba
  sheba:
    port: 80
    replicas: 1
    ingress:
      annotations: {}
    repository:
      image: guydo/tmr-sheba-digest
      tag: latest
    volumeMappings:
      - relativePath: src/sheba/digest/tmr_digest
        containerPath: /opt/digest/tmr_digest
      - relativePath: src/common/tmr_common
        containerPath: /opt/common/tmr_common
    input:
      type: external
      external:
        secretName: sheba-connections
      internal:
        arc:
          repository:
            image: guydo/tmr-sheba-arc
            tag: latest
          nodePort: 31433
          volumeMappings:
            - relativePath: src/dev/sheba/arc-db/initialize
              containerPath: /opt/arc-db/initialize
        chameleon:
          repository:
            image: guydo/tmr-sheba-chameleon
            tag: latest
          nodePort: 31434
          volumeMappings:
            - relativePath: src/dev/sheba/chameleon/initialize
              containerPath: /opt/chameleon/initialize
        faker:
          port: 80
          repository:
            image: guydo/tmr-sheba-faker
            tag: latest
          volumeMappings:
            - relativePath: src/dev/sheba/faker/tmr_faker
              containerPath: /opt/faker/tmr_faker
            - relativePath: src/sheba/digest/tmr_digest
              containerPath: /opt/digest/tmr_digest
            - relativePath: src/common/tmr_common
              containerPath: /opt/common/tmr_common
mongo:
  port: 27017
  replicas: 1
  repository:
    image: mongo
    tag: latest
  nodePort: 32717
redis:
  port: 6379
  replicas: 1
  repository:
    image: redis
    tag: latest
  nodePort: 32679
