apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sheba.fullname" . }}
  labels:
    {{- include "sheba.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "sheba.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "sheba.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "sheba.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: 'check-dal'
          image: {{ $.Values.global.helpers.busybox.image }}
          command: ["sh", "-c", "until nc -z {{ .Values.global.fullname.dal }} {{ .Values.global.servicePort.dal }}; do sleep 1; done"]
        {{- if .Values.input.internal.enabled }}
        - name: 'check-chameleon'
          image: {{ $.Values.global.helpers.busybox.image }}
          command: ["sh", "-c", "until nc -z {{ .Values.global.fullname.chameleon }} {{ .Values.global.servicePort.chameleon }}; do sleep 1; done"]
        {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ if .Values.global.devMode.enabled }}{{ .Values.image.tag | default "dev" }}{{ else }}{{ .Values.image.tag | default .Chart.AppVersion }}{{ end }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: 'DAL_CONNECTION'
              value: '"http://{{ .Values.global.fullname.dal }}:{{ .Values.global.servicePort.dal }}/dal"'
            - name: 'CHAMELEON_CONNECTION'
              {{- if .Values.input.internal.enabled }}
              value: '"mssql+pyodbc://sa:Password123@{{ .Values.global.fullname.chameleon }}:{{ .Values.global.servicePort.chameleon }}/dwh?driver=ODBC+Driver+18+for+SQL+Server&trustServerCertificate=yes"'
              {{- else }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.input.external.secretName }}
                  key: {{ .Values.input.external.secretKey }}
              {{- end }}
            - name: 'ORACLE_CONNECTION'
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.input.oracle.secretName }}
                  key: {{ .Values.input.oracle.secretKey }}
            - name: 'PORT'
              value: '80'
            - name: 'DEBUG'
              value: {{ if .Values.global.devMode.enabled }} '1' {{ else }} '0' {{ end }}
            {{- if .Values.sentry.enabled }}
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  key: {{ .Values.sentry.secretKey }}
                  name: {{ .Values.sentry.secretName }}
            - name: SENTRY_CA_CERT_PATH
              value: '/opt/ssl/cert_ca.pem'
            {{- end }}
          {{- if or .Values.global.devMode.enabled .Values.sentry.enabled }}
          volumeMounts: {{ if not (or (and .Values.global.devMode.enabled (len .Values.devMappings)) .Values.sentry.enabled) }} [] {{ end }}
            {{- if .Values.global.devMode.enabled}}
            {{- range $index, $value := .Values.devMappings }}
            - name: 'volume-{{ $index }}'
              mountPath: {{ $value.containerPath }}
            {{- end }}
            {{- end }}
            {{- if .Values.sentry.enabled }}
            - name: 'volume-sentry-ca'
              mountPath: '/opt/ssl'
            {{- end }}
          {{- end }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /digest/docs
              port: http
          readinessProbe:
            httpGet:
              path: /digest/docs
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- if or .Values.global.devMode.enabled .Values.sentry.enabled }}
      volumes: {{ if not (or (and .Values.global.devMode.enabled (len .Values.devMappings)) .Values.sentry.enabled) }} [] {{ end }}
        {{- if .Values.global.devMode.enabled}}
        {{- range $index, $value := .Values.devMappings }}
        - name: 'volume-{{ $index }}'
          hostPath:
            path: {{ $.Values.global.devMode.baseDir }}/{{ $value.relativePath }}
            type: DirectoryOrCreate
        {{- end }}
        {{- end }}
        {{- if .Values.sentry.enabled }}
        - name: 'volume-sentry-ca'
          configMap:
            name: {{ .Values.sentry.caCertConfigMapName }}
        {{- end }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
