services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379

  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db

  chameleon-sheba:  # Stand in for the real DBs
    profiles:
      - sheba
    build:
      dockerfile: dev/sheba/chameleon/Dockerfile
      context: ../src
    volumes:
      - "./dev/sheba/chameleon/initialize:/opt/chameleon/initialize"
    environment:
      - "MSSQL_TCP_PORT=1433"
      - "SA_PASSWORD=Password123"
      - "TZ=UTC"
    ports:
      - "1433:1433"

  chameleon-demo: # Stand in for the real DBs
    profiles:
      - demo
    build:
      dockerfile: dev/demo/demo-db/Dockerfile
      context: ../src
    volumes:
      - "./dev/demo/demo-db/initialize:/opt/dmo-db/initialize"
    environment:
      - "MSSQL_TCP_PORT=1433"
      - "SA_PASSWORD=Password123"
      - "TZ=UTC"
    ports:
      - "1433:1433"


volumes:
  mongo-data:
    name: mongo-data
