services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379

  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db

  chameleon-sheba:
    profiles:
      - sheba
    build:
      dockerfile: dev/sheba/chameleon/Dockerfile
      context: ../src
    volumes:
      - chameleon-sheba:/var/opt/mssql
    environment:
      - "MSSQL_TCP_PORT=1433"
      - "SA_PASSWORD=Password123"
      - "TZ=UTC"
    ports:
      - "1433:1433"

  sentry-postgres:
    image: 'postgres:latest'
    environment:
      POSTGRES_USER: sentry
      POSTGRES_PASSWORD: sentry
      POSTGRES_DB: sentry
    volumes:
      - /srv/sentry/postgres:/var/lib/postgresql/data

  sentry-base:
    image: sentry
    container_name: sentry-base
    restart: unless-stopped
    depends_on:
      - redis
      - sentry-postgres
    links:
      - redis
      - sentry-postgres
    ports:
     - 9000:9000
    env_file:
      - sentry.env
    volumes:
      - /srv/sentry/sentry:/var/lib/sentry/files

  sentry-worker:
    image: 'sentry:latest'
    depends_on:
      - sentry-base
    links:
      - redis
      - sentry-postgres
    command: "sentry run worker"
    env_file:
      - sentry.env
    volumes:
      - /srv/sentry/sentry:/var/lib/sentry/files

  sentry-cron:
    image: 'sentry:latest'
    restart: unless-stopped
    depends_on:
      - sentry-base
    links:
      - redis
      - sentry-postgres
    command: "sentry run cron"
    env_file:
      - sentry.env
    volumes:
      - /srv/sentry/sentry:/var/lib/sentry/files

  chameleon-demo:
    profiles:
      - demo
    build:
      dockerfile: dev/demo/demo-db/Dockerfile
      context: ../src
    volumes:
      - chameleon-demo:/var/opt/mssql
    environment:
      - "MSSQL_TCP_PORT=1433"
      - "SA_PASSWORD=Password123"
      - "TZ=UTC"
    ports:
      - "1433:1433"

  # See the ldap_server Dockerfile for instructions.
  ldap:
    profiles:
      - ldap
    build:
      dockerfile: ./Dockerfile
      context: ./ldap_server
    ports:
      - "389:389"

volumes:
  mongo-data:
    name: mongo-data
  chameleon-sheba:
    name: chameleon-sheba
  chameleon-demo:
    name: chameleon-demo
