apiVersion: apps/v1
kind: Deployment
metadata:
  name: '{{ .Release.Name }}-frontend'
  labels:
    project: tmr
    component: frontend
    release: '{{ .Release.Name }}'
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      project: tmr
      component: frontend
      release: '{{ .Release.Name }}'
  template:
    metadata:
      labels:
        project: tmr
        component: frontend
        release: '{{ .Release.Name }}'
    spec:
      initContainers:
        - name: check-backend
          image: {{ .Values.global.helpers.busybox.image }}
          command:
            - sh
            - -c
            - |-
              OK=0
              echo "Checking backend port"
              while [ $OK != 1 ]; do
                  echo -n "."
                  nc -z {{ .Release.Name }}-backend {{ .Values.backend.port }} 2>&1 >/dev/null && OK=1 || sleep 1
              done
              echo
              echo "Done"
      containers:
        - name: frontend
          image: '{{ .Values.frontend.repository.image }}{{ if ne .Values.frontend.repository.tag "" }}:{{ .Values.frontend.repository.tag }}{{ end }}'
          ports:
            - name: frontend
              containerPort: {{ .Values.frontend.port }}
          readinessProbe:
            httpGet:
              port: {{ .Values.frontend.port }}
              path: /
            initialDelaySeconds: 60
            failureThreshold: 10
          volumeMounts: {{ if not (len .Values.frontend.volumeMappings) }}[]{{ end }}
            {{- range $index, $value := .Values.frontend.volumeMappings }}
            - name: 'volume-{{ $index }}'
              mountPath: {{ $value.containerPath }}
            {{end}}
      volumes: {{ if not (len .Values.frontend.volumeMappings) }}[]{{ end }}
        {{- range $index, $value := .Values.frontend.volumeMappings }}
        - name: 'volume-{{ $index }}'
          hostPath:
            path:  {{ $.Values.global.baseDir }}/{{ $value.relativePath }}
            type: DirectoryOrCreate
        {{end}}
