apiVersion: apps/v1
kind: Deployment
metadata:
  name: '{{ .Release.Name }}-mongo'
  labels:
    project: tmr
    component: mongo
    release: '{{ .Release.Name }}'
spec:
  replicas: {{ .Values.mongo.replicas }}
  selector:
    matchLabels:
      project: tmr
      component: mongo
      release: '{{ .Release.Name }}'
  template:
    metadata:
      labels:
        project: tmr
        component: mongo
        release: '{{ .Release.Name }}'
    spec:
      containers:
        - name: mongo
          image: '{{ .Values.mongo.repository.image }}{{ if ne .Values.mongo.repository.tag "" }}:{{ .Values.mongo.repository.tag }}{{ end }}'
          ports:
            - name: mongo
              containerPort: {{ .Values.mongo.port }}

