apiVersion: apps/v1
kind: Deployment
metadata:
  name: '{{ .Release.Name }}-redis'
  labels:
    component: redis
    project: tmr
    release: '{{ .Release.Name }}'
spec:
  replicas: {{ .Values.redis.replicas }}
  selector:
    matchLabels:
      component: redis
      project: tmr
      release: '{{ .Release.Name }}'
  template:
    metadata:
      labels:
        component: redis
        project: tmr
        release: '{{ .Release.Name }}'
    spec:
      containers:
        - name: redis
          image: '{{ .Values.redis.repository.image }}{{ if ne .Values.redis.repository.tag "" }}:{{ .Values.redis.repository.tag }}{{ end }}'
          ports:
            - name: redis
              containerPort: {{ .Values.redis.port }}
          readinessProbe:
            tcpSocket:
              port: {{ .Values.redis.port }}
