{{ if and (eq .Values.digest.type "sheba") (eq .Values.digest.sheba.input.type "internal") }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: '{{ .Release.Name }}-sheba-faker'
  labels:
    project: tmr
    component: sheba-faker
    release: '{{ .Release.Name }}'
spec:
  replicas: 1
  selector:
    matchLabels:
      project: tmr
      component: sheba-faker
      release: '{{ .Release.Name }}'
  template:
    metadata:
      labels:
        project: tmr
        component: sheba-faker
        release: '{{ .Release.Name }}'
    spec:
      initContainers:
        - name: check-sheba-arc
          image: {{ .Values.global.helpers.busybox.image }}
          command:
            - sh
            - -c
            - |-
              OK=0
              echo "Checking sheba-arc port"
              while [ $OK != 1 ]; do
                  echo -n "."
                  nc -z {{ .Release.Name }}-sheba-arc 1433 2>&1 >/dev/null && OK=1 || sleep 1
              done
              echo
              echo "Done"
      containers:
        - name: sheba-faker
          image: '{{ .Values.digest.sheba.input.internal.faker.repository.image }}{{ if ne .Values.digest.sheba.input.internal.faker.repository.tag "" }}:{{ .Values.digest.sheba.input.internal.faker.repository.tag }}{{ end }}'
          ports:
            - name: sheba-faker
              containerPort: {{ .Values.digest.sheba.input.internal.faker.port }}
          env:
            - name: ARC_CONNECTION
              value: '"mssql+pyodbc://sa:Password123@{{ .Release.Name }}-sheba-arc:1433/dwh?driver=ODBC+Driver+18+for+SQL+Server&trustServerCertificate=yes"'
          readinessProbe:
            httpGet:
              port: {{ .Values.digest.sheba.input.internal.faker.port }}
              path: /faker/docs
          volumeMounts: {{ if not (len .Values.digest.sheba.input.internal.faker.volumeMappings) }}[]{{ end }}
            {{- range $index, $value := .Values.digest.sheba.input.internal.faker.volumeMappings }}
            - name: 'volume-{{ $index }}'
              mountPath: {{ $value.containerPath }}
            {{end}}
      volumes: {{ if not (len .Values.digest.sheba.input.internal.faker.volumeMappings) }}[]{{ end }}
        {{- range $index, $value := .Values.digest.sheba.input.internal.faker.volumeMappings }}
        - name: 'volume-{{ $index }}'
          hostPath:
            path:  {{ $.Values.global.baseDir }}/{{ $value.relativePath }}
            type: DirectoryOrCreate
        {{end}}
{{ end }}