apiVersion: v1
kind: Service
metadata:
  name: {{ include "demo-db.fullname" . }}
  labels:
    {{- include "demo-db.labels" . | nindent 4 }}
spec:
  type: {{ if .Values.global.debug }}NodePort{{ else }}ClusterIP{{ end }}
  ports:
    - port: {{ .Values.global.servicePort.demoDB }}
      targetPort: {{ .Values.global.servicePort.demoDB }}
      {{- if .Values.global.debug }}
      nodePort: 31533
      {{- end }}
      protocol: TCP
      name: mssql
  selector:
    {{- include "demo-db.selectorLabels" . | nindent 4 }}
