apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "backend.fullname" . }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "backend.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "backend.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: 'check-mongo'
          image: {{ $.Values.global.helpers.busybox.image }}
          command: [ "sh", "-c", "until nc -z {{ .Values.global.fullname.mongo }} {{ .Values.global.servicePort.mongo }}; do sleep 1; done" ]
        - name: 'check-redis'
          image: {{ $.Values.global.helpers.busybox.image }}
          command: [ "sh", "-c", "until nc -z {{ .Values.global.fullname.redis }}-master {{ .Values.global.servicePort.redis }}; do sleep 1; done" ]
        - name: 'check-dal'
          image: {{ $.Values.global.helpers.busybox.image }}
          command: [ "sh", "-c", "until nc -z {{ .Values.global.fullname.dal }} {{ .Values.global.servicePort.dal }}; do sleep 1; done" ]
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ if .Values.global.devMode.enabled }}{{ .Values.image.tag | default "dev" }}{{ else }}{{ .Values.image.tag | default .Chart.AppVersion }}{{ end }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: 'MONGO_CONNECTION'
              value: '"mongodb://{{ .Values.global.fullname.mongo }}:{{ .Values.global.servicePort.mongo }}"'
            - name: 'REDIS_CONNECTION'
              value: '"redis://{{ .Values.global.fullname.redis }}-master:{{ .Values.global.servicePort.redis }}/0"'
            - name: 'DAL_CONNECTION'
              value: '"http://{{ .Values.global.fullname.dal }}:{{ .Values.global.servicePort.dal }}/dal"'
            - name: 'PORT'
              value: '80'
            - name: 'DEBUG'
              value: {{ if .Values.global.devMode.enabled }} '1' {{ else }} '0' {{ end }}
            {{- if .Values.sentry.enabled }}
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  key: {{ .Values.sentry.secretKey }}
                  name: {{ .Values.sentry.secretName }}
            {{- end }}
          {{- if .Values.global.devMode.enabled }}
          volumeMounts: {{ if not (len .Values.devMappings) }}[ ]{{ end }}
            {{- range $index, $value := .Values.devMappings }}
            - name: 'volume-{{ $index }}'
              mountPath: {{ $value.containerPath }}
            {{- end }}
          {{- end }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/docs
              port: http
          readinessProbe:
            httpGet:
              path: /api/docs
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- if .Values.global.devMode.enabled }}
      volumes: {{ if not (len .Values.devMappings) }}[ ]{{ end }}
        {{- range $index, $value := .Values.devMappings }}
        - name: 'volume-{{ $index }}'
          hostPath:
            path: {{ $.Values.global.devMode.baseDir }}/{{ $value.relativePath }}
            type: DirectoryOrCreate
        {{- end }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
