apiVersion: v1
kind: Service
metadata:
  name: {{ include "chameleon.fullname" . }}
  labels:
    {{- include "chameleon.labels" . | nindent 4 }}
spec:
  type: {{ if .Values.global.debug }}NodePort{{ else }}ClusterIP{{ end }}
  ports:
    - port: {{ .Values.global.servicePort.chameleon }}
      targetPort: {{ .Values.global.servicePort.chameleon }}
      {{- if .Values.global.debug }}
      nodePort: 31433
      {{- end }}
      protocol: TCP
      name: mssql
  selector:
    {{- include "chameleon.selectorLabels" . | nindent 4 }}
