services:
  backend:
    build:
      target: dev
      context: ./
      dockerfile: backend/Dockerfile
    volumes:
      - "./config:/opt/config"
      - "./backend/tmr:/opt/backend/tmr"
      - "./common/tmr_common:/opt/common/tmr_common"
    deploy:
      replicas: 1
    depends_on:
      - medical-dal
      - broadcast-redis

  medical-dal:
    build:
      target: dev
      context: ./
      dockerfile: medical_dal/Dockerfile
    volumes:
      - "./medical_dal/tmr:/opt/medical_dal/tmr"
      - "./common/tmr_common:/opt/common/tmr_common"
    deploy:
      replicas: 1
    depends_on:
      - mongo
      - broadcast-redis

  frontend:
    build:
      target: dev
      context: ./
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - "./frontend/tmr/src:/opt/frontend/tmr/src"
      - "./frontend/tmr/public:/opt/frontend/tmr/public"
    depends_on:
      - backend

  proxy:
    image: nginx:latest
    volumes:
      - "./proxy/conf.dev/:/etc/nginx/conf.d/"
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
      - frontend
      - medical-dal

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"

  broadcast-redis:
    image: redis:latest
    ports:
      - "6379:6379"

  dev:
    build:
      target: dev
      context: ./
      dockerfile: dev/Dockerfile




  owa:
    image: vladk1m0/docker-owa:latest
    container_name: open-web-analytics
    depends_on:
      - mysql
    networks:
      - owa_net
    ports:
      - 8090:80
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
  mysql:
    image: mysql:5.7
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=tamar
      - MYSQL_DATABASE=tamar_owa
      - MYSQL_USER=tamar
      - MYSQL_PASSWORD=tamar
    networks:
      - owa_net
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

networks:
  owa_net:
    driver: bridge
