services:
  dev:
    build:
      target: dev
      context: ./
      dockerfile: dev/Dockerfile

  matomo-db:
    image: mysql:8
    restart: unless-stopped
    ports:
      - '3306:3306'
    volumes:
      - matomo-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=tamar
    env_file:
      - ./matomo/matomo-db.env

  matomo-app:
    image: matomo:fpm-alpine
    restart: unless-stopped
    volumes:
      #      - ./config:/var/www/html/config:rw
      #      - ./logs:/var/www/html/logs
      - matomo:/var/www/html
    environment:
      - MATOMO_DATABASE_HOST=db
    env_file:
      - ./matomo/matomo-db.env
    links:
      - "matomo-db:db"

  matomo-web:
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - matomo:/var/www/html:ro
      # see https://github.com/matomo-org/matomo-nginx
      - ./matomo/matomo.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 8090:80
    depends_on:
      - matomo-db
    links:
      - "matomo-app:app"

volumes:
  matomo-db:
  matomo: