services:
  backend:
    build:
      target: dev
      context: ./
      dockerfile: backend/Dockerfile
    ports:
      - "8000:80"
    volumes:
      - "./backend/tmr:/opt/backend/tmr"
      - "./config:/opt/config"
      - "./common/tmr_common:/opt/common/tmr_common"
    depends_on:
      - medical-dal
      - broadcast-redis

  medical-dal:
    build:
      target: dev
      context: ./
      dockerfile: medical_dal/Dockerfile
    ports:
      - "8010:80"
    volumes:
      - "./medical_dal/tmr:/opt/medical_dal/tmr"
      - "./common/tmr_common:/opt/common/tmr_common"
    depends_on:
      - medical-db
      - broadcast-redis

  frontend:
    build:
      target: dev
      context: ./
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - "./frontend/tmr/src:/opt/frontend/tmr/src"
      - "./frontend/tmr/public:/opt/frontend/tmr/public"
    depends_on:
      - backend

  proxy:
    image: nginx:latest
    volumes:
      - "./proxy/conf.dev/:/etc/nginx/conf.d/"
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
      - frontend
      - medical-dal

  medical-db:
    image: mongo:latest
    ports:
      - "27017:27017"

  broadcast-redis:
    image: redis:latest
    ports:
      - "6379:6379"
        
  dev:
    build:
      target: dev
      context: ./
      dockerfile: dev/Dockerfile
    