volumes:
  sqlpad:


services:


  faker:
    build:
      target: dev
      context: ./
      dockerfile: sheba/faker/Dockerfile
    environment:
      - "CHAMELEON_CONNECTION_STRING=mssql+pyodbc://sa:Password123@sbwnd167f:1433/dwh?driver=ODBC+Driver+18+for+SQL+Server&trustServerCertificate=yes"
    volumes:
      - "./common/tmr_common:/opt/common/tmr_common"
      - "./sheba/ingress/tmr_ingress:/opt/ingress/tmr_ingress"
      - "./sheba/faker/tmr_faker:/opt/faker/tmr_faker"
    ports:
      - "8040:80"
    depends_on:
      - arc-db

  ingress:
    environment:
      - "CHAMELEON_CONNECTION_STRING=mssql+pyodbc://sa:Password123@sbwnd167f:1433/dwh?driver=ODBC+Driver+18+for+SQL+Server&trustServerCertificate=yes"
    depends_on:
      - arc-db

  proxy:
    volumes:
      - "./sheba/faker/conf.dev/location/:/etc/nginx/location.d/faker/"
      - "./sheba/faker/conf.dev/upstream/:/etc/nginx/upstream.d/faker/"
    depends_on:
      - faker

  arc-db:
    hostname: sbwnd167f
    build:
      context: ./
      dockerfile: sheba/arc-db/Dockerfile
    volumes:
      - "./sheba/arc-db/initialize:/opt/arc-db/initialize"
    environment:
      - "MSSQL_TCP_PORT=1433"
      - "SA_PASSWORD=Password123"
      - "TZ=UTC"
    ports:
      - "1433:1433"
    depends_on:
      - chameleon

  chameleon:
    hostname: sbwnd81c
    build:
      context: ./
      dockerfile: sheba/chameleon/Dockerfile
    volumes:
      - "./sheba/chameleon/initialize:/opt/chameleon/initialize"
    environment:
      - "MSSQL_TCP_PORT=1433"
      - "SA_PASSWORD=Password123"
      - "TZ=UTC"
    ports:
      - "1434:1433"

  sqlpad:
    links:
      - "arc-db:arc-db"
      - "chameleon:chameleon"
