services:
  backend:
    build:
      target: dev
      context: ./
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - "./backend/tmr:/opt/backend/tmr"

  frontend:
    build:
      target: dev
      context: ./
      dockerfile: frontend/Dockerfile

  proxy:
    image: nginx:latest
    volumes:
      - "./proxy/conf/:/etc/nginx.conf/"

  bootstrap:
    build:
      target: dev
      context: ./
      dockerfile: bootstrap/Dockerfile
    volumes:
      - "./bootstrap/bootstrap:/opt/bootstrap/bootstrap"

  medical-db:
    image: mongo:latest
    ports:
      - "27017:27017"
