services:

  ingress:
    build:
      target: dev
      context: ./
      dockerfile: sheba/ingress/Dockerfile
    environment:
      - "CHAMELEON_CONNECTION_STRING=foo"
    volumes:
      - "./common/tmr_common:/opt/common/tmr_common"
      - "./sheba/ingress/tmr_ingress:/opt/ingress/tmr_ingress"
    ports:
      - "8020:80"
    depends_on:
      - medical-dal

  proxy:
    volumes:
      - "./sheba/ingress/conf.dev/location/:/etc/nginx/location.d/ingress/"
      - "./sheba/ingress/conf.dev/upstream/:/etc/nginx/upstream.d/ingress/"
    depends_on:
      - ingress

  sqlpad:
    image: sqlpad/sqlpad
    environment:
      - "SQLPAD_PORT=80"
      - "SQLPAD_ADMIN=admin@sqlpad.com"
      - "SQLPAD_ADMIN_PASSWORD=Password123"
      - "SQLPAD_BASE_URL=/sqlpad"
    volumes:
      - "sqlpad:/var/lib/sqlpad"
    ports:
      - "8030:80"