volumes:
  sqlpad:


services:


  faker:
    build:
      target: dev
      context: ./
      dockerfile: sheba/faker/Dockerfile
    environment:
      - "CHAMELEON_CONNECTION_STRING=mssql+pyodbc://sa:Password123@chameleon:1433/chameleon_db?driver=ODBC+Driver+18+for+SQL+Server&trustServerCertificate=yes"
    volumes:
      - "./common/tmr_common:/opt/common/tmr_common"
      - "./sheba/ingress/tmr_ingress:/opt/ingress/tmr_ingress"
      - "./sheba/faker/tmr_faker:/opt/faker/tmr_faker"
    ports:
      - "8040:80"
    depends_on:
      - chameleon

  ingress:
    environment:
      - "CHAMELEON_CONNECTION_STRING=mssql+pyodbc://sa:Password123@chameleon:1433/chameleon_db?driver=ODBC+Driver+18+for+SQL+Server&trustServerCertificate=yes"
    depends_on:
      - chameleon

  proxy:
    volumes:
      - "./sheba/faker/conf.dev/location/:/etc/nginx/location.d/faker/"
      - "./sheba/faker/conf.dev/upstream/:/etc/nginx/upstream.d/faker/"
    depends_on:
      - faker

  chameleon:
    build:
      context: ./
      dockerfile: sheba/chameleon/Dockerfile
    volumes:
      - "./sheba/chameleon/initialize:/opt/chameleon/initialize"
    environment:
      - "MSSQL_TCP_PORT=1433"
      - "SA_PASSWORD=Password123"
    ports:
      - "1433:1433"
