services:
  mongo:
    image: mongo:latest

  redis:
    image: redis:latest

  dal:
    build:
      context: ./
      dockerfile: dal/Dockerfile
    image: "guydo/tmr-dal:${TAG:-latest}"
    environment:
      - 'MONGO_CONNECTION={"host": "mongo"}'
      - 'REDIS_CONNECTION="redis://redis/1"'

  backend:
    build:
      context: ./
      dockerfile: backend/Dockerfile
    image: "guydo/tmr-backend:${TAG:-latest}"
    environment:
      - 'MONGO_CONNECTION={"host": "mongo"}'
      - 'REDIS_CONNECTION="redis://redis/0"'
      - 'DAL_URL="http://dal/dal"'
      - 'WS_URL="ws://dal/dal/sync/ws"'

  frontend:
    build:
      context: ./
      dockerfile: frontend/Dockerfile
    image: "guydo/tmr-frontend:${TAG:-latest}"

