services:
  backend:
    build:
      target: dev
      context: ./
      dockerfile: backend/Dockerfile

  frontend:
    build:
      target: dev
      context: ./
      dockerfile: frontend/Dockerfile

  proxy:
    image: nginx:latest
    volumes:
      - "./proxy/conf/:/etc/nginx.conf/"

  bootstrap:
    build:
      target: dev
      context: ./
      dockerfile: bootstrap/Dockerfile

  medical-db:
    image: mongo:latest
    ports:
      - "27017:27017"
