volumes:
  matomo-db:
  matomo:

services:
  dev:
    build:
      target: dev
      context: ../
      dockerfile: dev/Dockerfile

  matomo-db:
    image: mysql:8
    restart: unless-stopped
    ports:
      - '3306:3306'
    volumes:
      - matomo-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=tamar
    env_file:
      - ./matomo/matomo-db.env

  matomo-app:
    image: matomo:fpm-alpine
    restart: unless-stopped
    volumes:
      #      - ./config:/var/www/html/config:rw
      #      - ./logs:/var/www/html/logs
      - matomo:/var/www/html
    environment:
      - MATOMO_DATABASE_HOST=db
    env_file:
      - ./matomo/matomo-db.env
    links:
      - "matomo-db:db"

  matomo-web:
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - matomo:/var/www/html:ro
      # see https://github.com/matomo-org/matomo-nginx
      - ./matomo/matomo.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 8090:80
    depends_on:
      - matomo-db
    links:
      - "matomo-app:app"

  proxy:
    image: nginx:latest
    volumes:
      - "./proxy/conf.dev/:/etc/nginx/conf.d/"
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
      - frontend
      - dal

  sqlpad:
    image: sqlpad/sqlpad
    environment:
      - "SQLPAD_PORT=80"
      - "SQLPAD_ADMIN=admin@sqlpad.com"
      - "SQLPAD_ADMIN_PASSWORD=Password123"
      - "SQLPAD_BASE_URL=/sqlpad"
    ports:
      - "8030:80"

  mongo:
    extends:
      service: mongo
      file: ../docker-compose.common.yml
    ports:
      - "27017:27017"

  redis:
    extends:
      service: redis
      file: ../docker-compose.common.yml
    ports:
      - "6379:6379"

  dal:
    extends:
      service: dal
      file: ../docker-compose.common.yml
    image: "guydo/tmr-dal:${TAG:-local}"
    volumes:
      - "../dal/tmr:/opt/dal/tmr"
      - "../common/tmr_common:/opt/common/tmr_common"
    build:
      target: dev

  backend:
    extends:
      service: backend
      file: ../docker-compose.common.yml
    image: "guydo/tmr-backend:${TAG:-local}"
    volumes:
      - "./config:/opt/config"
      - "../backend/tmr:/opt/backend/tmr"
      - "../common/tmr_common:/opt/common/tmr_common"
    build:
      target: dev

  frontend:
    extends:
      service: frontend
      file: ../docker-compose.common.yml
    image: "guydo/tmr-frontend:${TAG:-local}"
    volumes:
      - "../frontend/tmr/src:/opt/frontend/tmr/src"
      - "../frontend/tmr/public:/opt/frontend/tmr/public"
    build:
      target: dev
