apiVersion: v1
kind: Service
metadata:
  name: {{ include "arc.fullname" . }}
  labels:
    {{- include "arc.labels" . | nindent 4 }}
spec:
  type: {{ if .Values.global.debug }}NodePort{{ else }}ClusterIP{{ end }}
  ports:
    - port: {{ .Values.global.servicePort.arc }}
      targetPort: {{ .Values.global.servicePort.arc }}
      {{- if .Values.global.debug }}
      nodePort: 31434
      {{- end }}
      protocol: TCP
      name: mssql
  selector:
    {{- include "arc.selectorLabels" . | nindent 4 }}
